import { sqliteTable, integer, text } from 'drizzle-orm/sqlite-core';

const assets = sqliteTable('assets', {
  id: integer('id', { mode: 'number' }),
  market: text('market'),
  third: integer('third', { mode: 'number' }),
  contract_nr: integer('contract_nr', { mode: 'number' }),
  contract_status: text('contract_status', { length: 3 }),
  machine_active: integer('machine_active', { mode: 'boolean' }),
  start_date: text('start_date'),
  end_date: text('end_date'),
  contract_type: text('contract_type'),
  contract_desc: text('contract_desc'),
  agent_nr: integer('agent_nr', { mode: 'number' }),
  agent: text('agent'),
  local_agent_nr: integer('local_agent_nr', { mode: 'number' }),
  local_agent: text('local_agent'),
  install_by_nr: integer('install_by_nr', { mode: 'number' }),
  install_by: text('install_by'),
  signed_by_nr: integer('signed_by_nr', { mode: 'number' }),
  signed_by: text('signed_by'),
  lead_by_nr: integer('lead_by_nr', { mode: 'number' }),
  lead_by: text('lead_by'),
  linked_package: integer('linked_package', { mode: 'number' }),
  comp_linked: text('comp_linked'),
  comp_linked_desc: text('comp_linked_desc'),
  machine_serial_nr: text('machine_serial_nr'),
  category_1: integer('category_1', { mode: 'number' }),
  category_1_desc: text('category_1_desc'),
  category_2: integer('category_2', { mode: 'number' }),
  category_2_desc: text('category_2_desc'),
  comments: text('comments'),
  machine_product_code: text('machine_product_code'),
  vat_nr: text('vat_nr'),
  model_id: integer('model_id', { mode: 'number' }),
  model_short_name: text('model_short_name'),
  model_name: text('model_name'),
  model_group_name: text('model_group_name'),
  model_group_parent_name: text('model_group_parent_name'),
  address_nr: integer('address_nr', { mode: 'number' }),
});

export default assets;
