import { integer, text, sqliteTable } from 'drizzle-orm/sqlite-core';

const contracts = sqliteTable('contracts', {
  id: integer('id', { mode: 'number' }).notNull(),
  market: text('market').notNull(),
  third: integer('third').notNull(),
  contract_nr: integer('contract_nr').notNull(),
  contract_status: text('contract_status', { length: 3 }).notNull(),
  machine_active: integer('machine_active', { mode: 'boolean' }).notNull(),
  start_date: text('start_date').notNull(),
  end_date: text('end_date').notNull(),
  contract_type: text('contract_type').notNull(),
  contract_desc: text('contract_desc').notNull(),
  agent_nr: integer('agent_nr').notNull(),
  agent: text('agent').notNull(),
  local_agent_nr: integer('local_agent_nr').notNull(),
  local_agent: text('local_agent').notNull(),
  install_by_nr: integer('install_by_nr').notNull(),
  install_by: text('install_by').notNull(),
  signed_by_nr: integer('signed_by_nr').notNull(),
  signed_by: text('signed_by').notNull(),
  lead_by_nr: integer('lead_by_nr').notNull(),
  lead_by: text('lead_by').notNull(),
  linked_package: integer('linked_package').notNull(),
  comp_linked: text('comp_linked').notNull(),
  comp_linked_desc: text('comp_linked_desc').notNull(),
  machine_serial_nr: text('machine_serial_nr').notNull(),
  category_1: integer('category_1').notNull(),
  category_1_desc: text('category_1_desc').notNull(),
  category_2: integer('category_2').notNull(),
  category_2_desc: text('category_2_desc').notNull(),
  comments: text('comments').notNull(),
  machine_product_code: text('machine_product_code').notNull(),
  vat_nr: text('vat_nr').notNull(),
  model_id: integer('model_id').notNull(),
  address_nr: integer('address_nr').notNull(),
});

export default contracts;
